language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

before_script:
  - travis_retry composer install --prefer-source --no-interaction

script: composer test
